### ISSUE TITLE
Reading binary files.

### ISSUE THREAD

**Issue by axelande** [FarmLogs/pysobus#10]
This is more of a question,

Is this project intended to be used to read .bin files exported from tractors and harvesters etc?

If so, is it possible to se an example of reading .bin files or can anyone point me to another more suitable python project (if such is known)

**Comment by vollmarj** [comment]
This project provides some utilities for decoding raw iso11783 messages off the canbus in agricultural equipment. You will need your own mechanism for capturing data off the bus. 

This is different than the proprietary machine controller files that can be exported from the display. I think what you are looking for is something more like this: https://dev.agrigate.io/#introduction
