### ISSUE TITLE
have JD yield data in ISO format

### ISSUE THREAD

**Issue by RoboDonut** [FarmLogs/pysobus#4]
Hello, 

i have a bunch of yield data i would like to transform into something a but more usable that a binary file. I was hoping to use this library for such things but am not sure where to begin with my .bin and .xml files. any suggestions ?

**Comment by dbjohnson** [comment]
Hi there!  We can help you decode JD’s proprietary files, but unfortunately we can’t handle that step as part of this library - it requires integration with another vendor.  However, we do offer (for free), a service to import those files and view your yield maps at our website:  http://farmlogs.com <http://farmlogs.com/>.

- Bryan
