### ISSUE TITLE
Running Pysobus Parser

### ISSUE THREAD

**Issue by tjb8907** [FarmLogs/pysobus#6]
When I try to run your parser, I get an error that says AttributeError: module 'spanner' has no attribute 'tables'

Any Ideas?

Trying to run in on python 3.5.2 if that makes a difference. 

I'm somewhat of a python newbie, but I'm trying to decode some GPS CAN messages that I've captured.

**Comment by tjb8907** [comment]
![image](https://cloud.githubusercontent.com/assets/5883859/18806746/6eeec86a-81fb-11e6-9b7a-d474651a63bf.png)

**Comment by kochb** [comment]
Sorry about that, the dependency was cleaned up in #7.  If you grab the latest master it should run just fine.
