### ISSUE TITLE
A few John Deere messages to add to your table

### ISSUE THREAD

**Issue by torriem** [FarmLogs/pysobus#9]
Here are a few messages that StarFire seems to use.  I'm not sure how spn ids work, but I can provide spn numbers for the standard messages used here.

Src addr 28, dest addr 255, PGN 59904 - vehicle position
- industry standard pgn
- bytes 0-3 - latitude, divide by 10000000 and subtract 210 (spn 584)
- bytes 4-7 - longitude, divide by 10000000 and subtract 210 (spn 585)

src addr 28, dest addr 255, PGN 65256 - speed and direction (industry standard)
- bytes 0-1 - heading, 1/128 degrees per bit (spn 165)
- bytes 2-3 - speed, 1/256 kph per bit (spn 517)
- bytes 4-5 - pitch, 1/128 degrees per bit -210 degrees offset (spn 583)
- bytes 6-7 - altitude, 0.125 m per bit -2500 offset (spn 580)

src addr 28, dest addr 255, PGN 65254 - data and time (industry standard)
- byte 0 - seconds, 0.25 seconds per bit (spn 959)
- byte 1 - minutes, 1 minute per bit (spn 960)
- byte 2 - hours, 1 hour per bit (spn 961)
- byte 3 - month, 1 month per bit (spn 963)
- byte 4 - day, 0.25 days per bit (spn 962)
- byte 5 - year, add 1985 (spn 964)
- byte 6 - local minute offset, -125 offset (spn 1601)
- byte 7 - local hour offset, -125 offset (spn 1602)

Src addr 28, dest addr 255, PGN 65535
- byte 0 - 0x53
- byte 1 - unknown
- byte 2 - unknown
- byte 3 - high nibble fix type flag (0x3 for WAAS, 0x4 for SF1), low nibble accuracy level (0-a).
- byte 4 - fix type flag.  0x40 for SF1, 0x0 for WAAS
- bytes 5-7, unknown
byte 3 not only influences steering but also affects how the screen shows your accuracy, either as a little bar graph on older monitors, or the steering icon on newer screens. Steering requires both bytes 3 and 4 indicate at least SF1 accuracy.  With a microcontroller with two CAN interfaces, if you rewrite bytes 3 and 4 to say they are SF1, you can get steering to work with WAAS only (albeit with reduced accuracy).  Might be something to extend the life of units that are stuck with ITC receivers which stop working  with SF1 next year.

**Comment by kochb** [comment]
We would accept a PR that implements these changes.

**Comment by torriem** [comment]
Sounds good. I'll do that eventually. But it will be quite a while.
